name: cactus_example
description: "Demonstrates how to use the cactus flutter plugin."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  path_provider: ^2.0.0
  image_picker: ^1.1.2

  cactus:
    path: ../../cactus-flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.13.1" # Check for the latest version on pub.dev

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"